# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0002_auto_20150611_1109")]

    operations = [
        migrations.AlterField(
            model_name="sitefile",
            name="file",
            field=models.FileField(upload_to=b"pages/%Y/%m"),
        )
    ]
