# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0003_auto_20160126_1350")]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text=b"Uncheck this to remove this item without actually deleting it.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name=b"creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name=b"last modification time"
                    ),
                ),
                ("file", models.FileField(upload_to=b"pages/%Y/%m")),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="unitpages.Page"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
