# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0004_asset")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text=b"The parent page for this page, if it has one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="unitpages.Page",
            ),
        )
    ]
