# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0006_auto_20170829_0914")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="url",
            field=models.CharField(max_length=100, null=True, verbose_name="URL"),
        )
    ]
