# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0008_auto_20170829_0915")]

    operations = [
        migrations.RemoveField(model_name="page", name="parent"),
        migrations.RemoveField(model_name="page", name="slug"),
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.CharField(
                db_index=True, default="-fixme-", max_length=100, verbose_name="URL"
            ),
            preserve_default=False,
        ),
    ]
