# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0009_auto_20170829_0944")]

    operations = [
        migrations.AlterField(
            model_name="sitefile",
            name="slug",
            field=models.SlugField(
                help_text="An identifer for this resource that will be used in urls.  Must be globablly unique for all site files.  Use lower case, dashes, and numbers only.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="URL fragment",
            ),
        )
    ]
