# Generated by Django 2.1.7 on 2019-02-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("unitpages", "0010_auto_20170829_1045")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="short_title",
            field=models.CharField(
                blank=True, help_text="A much shorter alternate title", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="page",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="unitpages.Page",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(
                blank=True,
                help_text='This will be processed as <a href="/rst-help/" target="_blank">ReStructuredText</a>',
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(help_text="A meaningful title", max_length=100),
        ),
    ]
